title: hg.fi
url: "https://hg.fi"
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
lang: en
